version: '3'

services:
  db:
    image: postgres

  backend:
    build:  
      context: ./backend/
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/src/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend